---
- name: Deploy Dockerized App
  hosts: web
  become: true

  tasks:

    - name: Create app directory
      file:
        path: /home/ubuntu/app
        state: directory

    - name: Copy application files
      copy:
        src: ../app/
        dest: /home/ubuntu/app/

    - name: Copy nginx config
      copy:
        src: ../nginx/default.conf
        dest: /home/ubuntu/app/default.conf

    - name: Copy Dockerfile
      copy:
        src: ../docker/Dockerfile
        dest: /home/ubuntu/app/Dockerfile

    - name: Build Docker image
      command: docker build -t devops-app /home/ubuntu/app

    - name: Stop existing container (if any)
      ignore_errors: yes
      command: docker stop devops-container

    - name: Remove existing container (if any)
      ignore_errors: yes
      command: docker rm devops-container

    - name: Run Docker container
      command: docker run -d -p 80:80 --name devops-container devops-app
